// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";

/**
 * @title MedoraCentral
 * @dev Central registry and verification contract for Medora supply chain
 * @notice This contract manages batch registration, hash chaining, and final verification
 */
contract MedoraCentral is AccessControl {
    using ECDSA for bytes32;
    using MessageHashUtils for bytes32;

    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");
    bytes32 public constant PRODUCER_ROLE = keccak256("PRODUCER_ROLE");
    bytes32 public constant INTERNAL_VERIFIER_ROLE = keccak256("INTERNAL_VERIFIER_ROLE");

    // Custom errors
    error BatchAlreadyExists(bytes32 batchId);
    error BatchNotFound(bytes32 batchId);
    error InvalidHashChain();
    error UnauthorizedAction(address actor, string action);

    // Struct to store complete batch information
    struct Batch {
        bytes32 currentHash; // Current hash in the chain
        bytes32 finalHash; // Final hash after all verifications
        address producer; // Original producer address
        address distributor; // Verified distributor address
        address retailer; // Verified retailer address
        address firstCustomer; // First customer who verified
        bool isFinalized; // Whether the chain is complete
        uint256 createdAt; // When batch was created
        uint256 finalizedAt; // When chain was completed
        bool exists; // Existence flag
    }

    // Verification signatures for each stage
    struct VerificationSignatures {
        bytes producerSig; // Producer's signature of initial hash
        bytes distributorSig; // Distributor's signature
        bytes retailerSig; // Retailer's signature
        bytes customerSig; // Customer's signature
    }

    // Mapping from batch ID to batch data
    mapping(bytes32 => Batch) public batches;

    // Mapping from batch ID to verification signatures
    mapping(bytes32 => VerificationSignatures) public batchSignatures;

    // Events
    event BatchRegistered(
        bytes32 indexed batchId,
        address indexed producer,
        bytes32 initialHash,
        uint256 timestamp
    );

    event DistributorVerified(
        bytes32 indexed batchId,
        address indexed distributor,
        bytes32 newHash,
        uint256 timestamp
    );

    event RetailerVerified(
        bytes32 indexed batchId,
        address indexed retailer,
        bytes32 newHash,
        uint256 timestamp
    );

    event CustomerVerified(
        bytes32 indexed batchId,
        address indexed customer,
        bytes32 finalHash,
        uint256 timestamp
    );

    event BatchFinalized(
        bytes32 indexed batchId,
        bytes32 finalHash,
        uint256 timestamp
    );

    /**
     * @dev Constructor sets up initial roles
     */
    constructor() {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(ADMIN_ROLE, msg.sender);
    }

    /**
     * @dev Modifier to check if batch exists
     */
    modifier batchExists(bytes32 batchId) {
        if (!batches[batchId].exists) {
            revert BatchNotFound(batchId);
        }
        _;
    }

    /**
     * @notice Register a new medicine batch (called by ProducerContract)
     * @param batchId Unique identifier for the batch
     * @param initialHash Initial hash generated by producer (medicine data + producer signature)
     * @param producer Address of the producer
     * @param signature Producer's signature of the hash
     */
    function registerBatch(
        bytes32 batchId,
        bytes32 initialHash,
        address producer,
        bytes calldata signature
    ) external onlyRole(PRODUCER_ROLE) {
        if (batches[batchId].exists) {
            revert BatchAlreadyExists(batchId);
        }

        // Verify producer signature (or trust internal verifier)
        if (!hasRole(INTERNAL_VERIFIER_ROLE, msg.sender)) {
            bytes32 message = keccak256(abi.encodePacked(batchId, initialHash));
            bytes32 ethMessage = message.toEthSignedMessageHash();
            address recovered = ethMessage.recover(signature);

            if (recovered != producer) {
                revert UnauthorizedAction(producer, "Invalid signature");
            }
        }

        // Store batch data
        Batch storage newBatch = batches[batchId];
        newBatch.currentHash = initialHash;
        newBatch.producer = producer;
        newBatch.createdAt = block.timestamp;
        newBatch.exists = true;

        // Store signature
        batchSignatures[batchId].producerSig = signature;

        emit BatchRegistered(batchId, producer, initialHash, block.timestamp);
    }

    /**
     * @notice Verify batch at distributor stage
     * @param batchId ID of the batch
     * @param distributorHash Hash after distributor verification
     * @param distributor Address of the distributor
     * @param signature Distributor's signature
     */
    function verifyDistributor(
        bytes32 batchId,
        bytes32 distributorHash,
        address distributor,
        bytes calldata signature
    ) external batchExists(batchId) {
        if (!hasRole(INTERNAL_VERIFIER_ROLE, msg.sender) && !hasRole(ADMIN_ROLE, msg.sender)) {
            revert UnauthorizedAction(msg.sender, "Caller must be admin or internal verifier");
        }
        Batch storage batch = batches[batchId];

        if (batch.distributor != address(0)) {
            revert UnauthorizedAction(distributor, "Distributor already verified");
        }

        // Verify the hash chain (distributor hash should build on current hash)
        bytes32 expectedHash = keccak256(abi.encodePacked(batch.currentHash, distributor));
        if (distributorHash != expectedHash) {
            revert InvalidHashChain();
        }

        // Verify distributor signature (or trust internal verifier)
        if (!hasRole(INTERNAL_VERIFIER_ROLE, msg.sender)) {
            bytes32 message = keccak256(abi.encodePacked(batchId, distributorHash));
            bytes32 ethMessage = message.toEthSignedMessageHash();
            address recovered = ethMessage.recover(signature);

            if (recovered != distributor) {
                revert UnauthorizedAction(distributor, "Invalid signature");
            }
        }

        // Update batch
        batch.currentHash = distributorHash;
        batch.distributor = distributor;
        batchSignatures[batchId].distributorSig = signature;

        emit DistributorVerified(batchId, distributor, distributorHash, block.timestamp);
    }

    /**
     * @notice Verify batch at retailer stage
     * @param batchId ID of the batch
     * @param retailerHash Hash after retailer verification
     * @param retailer Address of the retailer
     * @param signature Retailer's signature
     */
    function verifyRetailer(
        bytes32 batchId,
        bytes32 retailerHash,
        address retailer,
        bytes calldata signature
    ) external batchExists(batchId) {
        if (!hasRole(INTERNAL_VERIFIER_ROLE, msg.sender) && !hasRole(ADMIN_ROLE, msg.sender)) {
            revert UnauthorizedAction(msg.sender, "Caller must be admin or internal verifier");
        }
        Batch storage batch = batches[batchId];

        if (batch.distributor == address(0)) {
            revert UnauthorizedAction(retailer, "Distributor must verify first");
        }

        if (batch.retailer != address(0)) {
            revert UnauthorizedAction(retailer, "Retailer already verified");
        }

        // Verify the hash chain
        bytes32 expectedHash = keccak256(abi.encodePacked(batch.currentHash, retailer));
        if (retailerHash != expectedHash) {
            revert InvalidHashChain();
        }

        // Verify retailer signature (or trust internal verifier)
        if (!hasRole(INTERNAL_VERIFIER_ROLE, msg.sender)) {
            bytes32 message = keccak256(abi.encodePacked(batchId, retailerHash));
            bytes32 ethMessage = message.toEthSignedMessageHash();
            address recovered = ethMessage.recover(signature);

            if (recovered != retailer) {
                revert UnauthorizedAction(retailer, "Invalid signature");
            }
        }

        // Update batch
        batch.currentHash = retailerHash;
        batch.retailer = retailer;
        batchSignatures[batchId].retailerSig = signature;

        emit RetailerVerified(batchId, retailer, retailerHash, block.timestamp);
    }

    /**
     * @notice Final verification by customer
     * @param batchId ID of the batch
     * @param finalHash Final hash after customer verification
     * @param customer Address of the customer
     * @param signature Customer's signature
     */
    function verifyCustomer(
        bytes32 batchId,
        bytes32 finalHash,
        address customer,
        bytes calldata signature
    ) external batchExists(batchId) {
        if (!hasRole(INTERNAL_VERIFIER_ROLE, msg.sender) && !hasRole(ADMIN_ROLE, msg.sender)) {
            revert UnauthorizedAction(msg.sender, "Caller must be admin or internal verifier");
        }
        Batch storage batch = batches[batchId];

        if (batch.retailer == address(0)) {
            revert UnauthorizedAction(customer, "Retailer must verify first");
        }

        if (batch.isFinalized) {
            revert UnauthorizedAction(customer, "Batch already finalized");
        }

        // Verify the hash chain
        bytes32 expectedHash = keccak256(abi.encodePacked(batch.currentHash, customer));
        if (finalHash != expectedHash) {
            revert InvalidHashChain();
        }

        // Verify customer signature (or trust internal verifier)
        if (!hasRole(INTERNAL_VERIFIER_ROLE, msg.sender)) {
            bytes32 message = keccak256(abi.encodePacked(batchId, finalHash));
            bytes32 ethMessage = message.toEthSignedMessageHash();
            address recovered = ethMessage.recover(signature);

            if (recovered != customer) {
                revert UnauthorizedAction(customer, "Invalid signature");
            }
        }

        // Finalize batch
        batch.finalHash = finalHash;
        batch.firstCustomer = customer;
        batch.isFinalized = true;
        batch.finalizedAt = block.timestamp;
        batchSignatures[batchId].customerSig = signature;

        emit CustomerVerified(batchId, customer, finalHash, block.timestamp);
        emit BatchFinalized(batchId, finalHash, block.timestamp);
    }

    /**
     * @notice Get complete batch details
     * @param batchId ID of the batch
     * @return batch Complete batch data
     * @return signatures All verification signatures
     */
    function getBatchDetails(bytes32 batchId)
        external
        view
        batchExists(batchId)
        returns (Batch memory batch, VerificationSignatures memory signatures)
    {
        return (batches[batchId], batchSignatures[batchId]);
    }

    /**
     * @notice Check if a batch is legitimate (exists and is properly verified)
     * @param batchId ID of the batch
     * @return isLegitimate True if batch exists and has valid verification chain
     * @return currentHash The current/latest hash in the chain
     * @return finalHash The final hash if batch is finalized
     */
    function verifyBatchAuthenticity(bytes32 batchId)
        external
        view
        returns (
            bool isLegitimate,
            bytes32 currentHash,
            bytes32 finalHash,
            bool isFinalized
        )
    {
        Batch storage batch = batches[batchId];
        if (!batch.exists) {
            return (false, bytes32(0), bytes32(0), false);
        }

        // Check if batch has valid verification chain
        bool hasValidChain = batch.producer != address(0) || batch.distributor != address(0) ||
                           batch.retailer != address(0) || batch.firstCustomer != address(0);

        return (hasValidChain, batch.currentHash, batch.finalHash, batch.isFinalized);
    }

    /**
     * @notice Get batch status with all participant addresses
     * @param batchId ID of the batch
     * @return producer Producer address
     * @return distributor Distributor address
     * @return retailer Retailer address
     * @return firstCustomer First customer address
     * @return isFinalized Whether batch is complete
     */
    function getBatchParticipants(bytes32 batchId)
        external
        view
        batchExists(batchId)
        returns (
            address producer,
            address distributor,
            address retailer,
            address firstCustomer,
            bool isFinalized
        )
    {
        Batch storage batch = batches[batchId];
        return (
            batch.producer,
            batch.distributor,
            batch.retailer,
            batch.firstCustomer,
            batch.isFinalized
        );
    }
}
