export const ManufacturerRegistryABI = [
  "constructor(address _centralMarketplace)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error InvalidAddress()",
  "error InvalidAmount()",
  "error LiquiditySeedFailed()",
  "error ManufacturerAlreadyRegistered(address wallet)",
  "error NotRegisteredManufacturer(address wallet)",
  "error ReentrancyGuardReentrantCall()",
  "error TokenAlreadyCreated(address manufacturer)",
  "error TokenCreationFailed()",
  "event LiquiditySeeded(address indexed manufacturer, address indexed tokenAddress, uint256 ethAmount, uint256 tokenAmount, uint256 timestamp)",
  "event ManufacturerRegistered(address indexed wallet, uint256 timestamp)",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "event TokenCreated(address indexed manufacturer, address indexed tokenAddress, string name, string symbol, uint256 totalSupply, uint256 basePrice, uint256 timestamp)",
  "function ADMIN_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function centralMarketplace() view returns (address)",
  "function createToken(string name, string symbol, uint256 totalSupply, uint256 basePrice) returns (address tokenAddress)",
  "function getAllManufacturers() view returns (address[])",
  "function getManufacturerCount() view returns (uint256)",
  "function getManufacturerToken(address wallet) view returns (address)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function getTokenMetadata(address tokenAddress) view returns (tuple(address tokenContract, string name, string symbol, uint256 totalSupply, uint256 basePrice, bool isActive))",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function isRegisteredManufacturer(address wallet) view returns (bool)",
  "function manufacturers(address) view returns (bool isRegistered, address tokenAddress, uint256 registrationTime)",
  "function registerManufacturer(address wallet)",
  "function registeredManufacturers(uint256) view returns (address)",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeRole(bytes32 role, address account)",
  "function seedLiquidity(address tokenAddress, uint256 tokenAmount) payable",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function tokenMetadata(address) view returns (address tokenContract, string name, string symbol, uint256 totalSupply, uint256 basePrice, bool isActive)"
];
