export const MedoraCentralABI = [
  "constructor()",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error BatchAlreadyExists(bytes32 batchId)",
  "error BatchNotFound(bytes32 batchId)",
  "error ECDSAInvalidSignature()",
  "error ECDSAInvalidSignatureLength(uint256 length)",
  "error ECDSAInvalidSignatureS(bytes32 s)",
  "error InvalidHashChain()",
  "error UnauthorizedAction(address actor, string action)",
  "event BatchFinalized(bytes32 indexed batchId, bytes32 finalHash, uint256 timestamp)",
  "event BatchRegistered(bytes32 indexed batchId, address indexed producer, bytes32 initialHash, uint256 timestamp)",
  "event CustomerVerified(bytes32 indexed batchId, address indexed customer, bytes32 finalHash, uint256 timestamp)",
  "event DistributorVerified(bytes32 indexed batchId, address indexed distributor, bytes32 newHash, uint256 timestamp)",
  "event RetailerVerified(bytes32 indexed batchId, address indexed retailer, bytes32 newHash, uint256 timestamp)",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "function ADMIN_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function INTERNAL_VERIFIER_ROLE() view returns (bytes32)",
  "function PRODUCER_ROLE() view returns (bytes32)",
  "function batchSignatures(bytes32) view returns (bytes producerSig, bytes distributorSig, bytes retailerSig, bytes customerSig)",
  "function batches(bytes32) view returns (bytes32 currentHash, bytes32 finalHash, address producer, address distributor, address retailer, address firstCustomer, bool isFinalized, uint256 createdAt, uint256 finalizedAt, bool exists)",
  "function getBatchDetails(bytes32 batchId) view returns (tuple(bytes32 currentHash, bytes32 finalHash, address producer, address distributor, address retailer, address firstCustomer, bool isFinalized, uint256 createdAt, uint256 finalizedAt, bool exists) batch, tuple(bytes producerSig, bytes distributorSig, bytes retailerSig, bytes customerSig) signatures)",
  "function getBatchParticipants(bytes32 batchId) view returns (address producer, address distributor, address retailer, address firstCustomer, bool isFinalized)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function registerBatch(bytes32 batchId, bytes32 initialHash, address producer, bytes signature)",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeRole(bytes32 role, address account)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function verifyBatchAuthenticity(bytes32 batchId) view returns (bool isLegitimate, bytes32 currentHash, bytes32 finalHash, bool isFinalized)"
];
