export const UserMarketplaceABI = [
  "constructor(address _centralMarketplace)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error InsufficientBalance(address token, uint256 required, uint256 available)",
  "error InsufficientOutput()",
  "error InvalidAddress()",
  "error InvalidAmount()",
  "error ReentrancyGuardReentrantCall()",
  "error SafeERC20FailedOperation(address token)",
  "error SlippageExceeded(uint256 expected, uint256 received)",
  "error TransferFailed()",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "event TokensPurchased(address indexed user, address indexed tokenAddress, uint256 ethIn, uint256 tokensOut, uint256 price, uint256 timestamp)",
  "event TokensSold(address indexed user, address indexed tokenAddress, uint256 tokensIn, uint256 ethOut, uint256 price, uint256 timestamp)",
  "function ADMIN_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function buyTokens(address tokenAddress, uint256 minAmountOut) payable",
  "function calculatePnL(address user, address tokenAddress) view returns (int256 pnl)",
  "function centralMarketplace() view returns (address)",
  "function getPoolState(address tokenAddress) view returns (uint256 ethReserve, uint256 tokenReserve, uint256 k, uint256 totalVolume, uint256 lastPrice)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function getTokenBalance(address user, address tokenAddress) view returns (uint256)",
  "function getUserPortfolio(address user) view returns (address[] tokens, uint256[] balances, uint256[] totalEthSpent, uint256[] currentValue)",
  "function getUserTransactionHistory(address user) view returns (tuple(address tokenAddress, bool isBuy, uint256 amountIn, uint256 amountOut, uint256 price, uint256 timestamp)[])",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeRole(bytes32 role, address account)",
  "function sellTokens(address tokenAddress, uint256 tokenAmount, uint256 minEthOut)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)"
];
